import {useState, useEffect} from 'react';
import {Link, NavLink, useLocation} from 'react-router-dom';
import {Building2, Menu, X, Plus, Globe2, ArrowUpRight, Heart, LayoutDashboard, LogOut} from 'lucide-react';
import {useApp} from '../context';
export const Logo = ({footer=false}) => <Link to="/" className="logo" data-testid={footer ? 'footer-logo' : 'header-logo'} aria-label="Global Estates home"><span className="logo-icon"><Building2 size={29} strokeWidth={1.3}/></span><span>Global<span className="logo-estates">Estates<span className="logo-dot">.</span></span></span></Link>;
export const Header = () => {
  const [open,setOpen] = useState(false), {user, logout} = useApp(), location=useLocation();
  useEffect(()=>{setOpen(false); window.scrollTo({top:0,behavior:'instant'});},[location.pathname, location.search]);
  const links=[['Home','/'],['Rent','/properties?category=Rent'],['Vacation','/properties?category=Vacation'],['Outings','/properties?category=Outings'],['Land','/properties?category=Land']];
  return <header className="header"><div className="header-inner"><Logo/><nav className="desktop-nav" aria-label="Main navigation">{links.map(([name,path])=><NavLink key={name} data-testid={`nav-${name.toLowerCase()}`} className={()=>(location.pathname+location.search === path ? 'active' : '')} to={path}>{name}</NavLink>)}</nav><div className="header-actions"><Link to="/saved" className="icon-link desktop-only" title="Saved places" aria-label="Saved places" data-testid="header-saved"><Heart size={19}/></Link><Link className="list-property-link" to="/list-property" data-testid="header-list-property"><Plus size={16}/><span>List your property</span></Link>{user ? <Link className="signin-link" to="/dashboard" data-testid="header-dashboard"><span className="avatar">{user.name[0]}</span><span className="desktop-only">My dashboard</span></Link> : <Link className="signin-link desktop-only" to="/signin" data-testid="header-signin">Sign in<ArrowUpRight size={15}/></Link>}<button className="mobile-menu-button" data-testid="mobile-menu-toggle" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>{open && <nav className="mobile-nav" data-testid="mobile-menu" aria-label="Mobile navigation">{links.map(([name,path])=><Link to={path} key={name} data-testid={`mobile-nav-${name.toLowerCase()}`}>{name}<ArrowUpRight size={16}/></Link>)}<Link to="/saved" data-testid="mobile-saved"><Heart size={16}/>Saved places</Link><Link to={user?'/dashboard':'/signin'} data-testid="mobile-account">{user?'My dashboard':'Sign in'}</Link>{user&&<button data-testid="mobile-logout" onClick={logout}><LogOut size={16}/>Sign out</button>}</nav>}</header>;
};
export const Footer = () => <footer className="footer"><div className="container footer-main"><div><Logo footer/><p data-testid="footer-tagline">Extraordinary places. Endless possibilities.</p></div><div className="footer-links"><Link to="/properties" data-testid="footer-explore">Explore properties<ArrowUpRight size={14}/></Link><Link to="/list-property" data-testid="footer-list">Become a host<ArrowUpRight size={14}/></Link><Link to="/dashboard" data-testid="footer-dashboard"><LayoutDashboard size={14}/>Owner dashboard</Link></div></div><div className="container footer-bottom"><span data-testid="copyright">© {new Date().getFullYear()} Global Estates. All rights reserved.</span><span data-testid="footer-global"><Globe2 size={14}/>Global marketplace<span className="dot-separator">·</span>Prices in KSh</span></div></footer>;