import {useEffect,useState,useCallback} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {Plus,Home,Wallet,CalendarDays,Mail,ArrowUpRight,Eye,Pencil,Trash2,LogOut,TrendingUp,Building2} from 'lucide-react';
import {toast} from 'sonner';
import {api,errorText,money,imageUrl} from '../lib/api';
import {useApp} from '../context';
import {Action,Loading,ErrorState,Empty} from '../components/Common';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
const tabs=[['properties','My properties',Home],['bookings','Bookings',CalendarDays],['payouts','Earnings & payouts',Wallet],['inquiries','Inbox',Mail]];
export default function Dashboard(){
  const {user,logout,meta}=useApp(),[params,setParams]=useSearchParams(),tab=params.get('tab')||'properties',[data,setData]=useState(null),[error,setError]=useState(''),[deleting,setDeleting]=useState(null),[busy,setBusy]=useState(false),[country,setCountry]=useState('KE');
  const load=useCallback(()=>{setError('');api.get('/owner/dashboard').then(r=>setData(r.data)).catch(e=>setError(errorText(e)));},[]);useEffect(load,[load]);
  const remove=async()=>{setBusy(true);try{await api.delete(`/properties/${deleting.id}`);toast.success('Property deleted.');setDeleting(null);load();}catch(e){toast.error(errorText(e));}finally{setBusy(false);}};
  const onboarding=async()=>{setBusy(true);try{const r=await api.post('/owner/onboarding',{country});window.location.assign(r.data.url);}catch(e){toast.error(errorText(e));setBusy(false);}};
  const payout=async id=>{setBusy(true);try{const r=await api.post(`/owner/payout/${id}`);toast.success(r.data.message||'Transfer confirmed');load();}catch(e){toast.error(errorText(e));}finally{setBusy(false);}};
  if(error)return <main className="container page"><ErrorState message={error} retry={load}/></main>;if(!data)return <Loading/>;
  const bookingFilter=params.get('property');const bookings=data.bookings.filter(b=>!bookingFilter||b.property_id===bookingFilter);
  return <main className="container page dashboard"><div className="page-heading"><div><div className="eyebrow muted" data-testid="dashboard-eyebrow">YOUR OWNER SPACE</div><h1 data-testid="dashboard-title">Hello, {user.name.split(' ')[0]}<span className="accent-dot">.</span></h1><p data-testid="dashboard-description">Great hosting starts with a little perspective.</p></div><div className="dashboard-top-actions"><Link to="/bookings" className="text-link" data-testid="my-trips-link">My trips<ArrowUpRight size={15}/></Link><button className="icon-link" title="Sign out" aria-label="Sign out" data-testid="dashboard-logout" onClick={logout}><LogOut size={18}/></button><Link className="action" to="/list-property" data-testid="dashboard-add-property"><Plus size={17}/>Add property</Link></div></div><div className="stat-grid">{[['Total properties',String(data.properties.length),Building2],['Booking revenue',money(data.revenue),TrendingUp],['Total earnings',money(data.earnings),Wallet],['Pending payouts',money(data.pending_payouts),CalendarDays]].map(([label,value,Icon],i)=><div className="stat" key={label}><div><span data-testid={`stat-label-${i}`}>{label}</span><Icon size={19}/></div><strong data-testid={`stat-value-${i}`}>{value}</strong></div>)}</div><div className="dashboard-tabs" role="tablist">{tabs.map(([value,label,Icon])=><button key={value} role="tab" aria-selected={tab===value} className={tab===value?'selected':''} data-testid={`dashboard-tab-${value}`} onClick={()=>setParams({tab:value})}><Icon size={16}/>{label}{value==='inquiries'&&data.inquiries.length>0&&<span>{data.inquiries.length}</span>}</button>)}</div>
  {tab==='properties'&&(data.properties.length?<div className="owner-properties">{data.properties.map(p=><article className="owner-property" key={p.id} data-testid={`owner-property-${p.id}`}><img src={imageUrl(p.images[0])} alt={p.title}/><div className="owner-property-copy"><div className="owner-badges"><span className={`status-pill ${p.status==='active'?'positive':''}`} data-testid={`owner-status-${p.id}`}>{p.status}</span><span className="plan-label" data-testid={`owner-plan-${p.id}`}>{p.listing_plan}</span></div><Link className="owner-property-title" to={`/properties/${p.id}${p.status!=='active'?'?preview=1':''}`} data-testid={`owner-title-${p.id}`}>{p.title}</Link><p data-testid={`owner-location-${p.id}`}>{p.location}, {p.country} · {p.category}</p><strong data-testid={`owner-price-${p.id}`}>{money(p.price)}</strong></div><div className="owner-actions"><Link className="icon-link" title="View property" aria-label="View property" to={`/properties/${p.id}${p.status!=='active'?'?preview=1':''}`} data-testid={`owner-view-${p.id}`}><Eye size={17}/></Link><Link className="icon-link" title="Edit property" aria-label="Edit property" to={`/list-property/${p.id}`} data-testid={`owner-edit-${p.id}`}><Pencil size={16}/></Link><button className="icon-link danger" title="Delete property" aria-label="Delete property" data-testid={`owner-delete-${p.id}`} onClick={()=>setDeleting(p)}><Trash2 size={16}/></button><button className="small-text-button" data-testid={`owner-bookings-${p.id}`} onClick={()=>setParams({tab:'bookings',property:p.id})}><CalendarDays size={14}/>Bookings</button><Link className="small-text-button gold-text" to={`/plans?property=${p.id}`} data-testid={`owner-promote-${p.id}`}>✦ Promote</Link></div></article>)}</div>:<Empty title="Your first property starts here" text="Share a place you love with a world of new guests."><Link className="action" to="/list-property" data-testid="dashboard-first-property"><Plus size={16}/>List your property</Link></Empty>)}
  {tab==='bookings'&&<>{bookingFilter&&<button className="text-link" data-testid="clear-booking-filter" onClick={()=>setParams({tab:'bookings'})}>Show bookings for all properties</button>}<BookingRows bookings={bookings}/></>}
  {tab==='inquiries'&&(data.inquiries.length?<div className="inquiries">{data.inquiries.map(i=><article className="inquiry" key={i.id}><div className="inquiry-heading"><span className="avatar">{i.customer_name[0]}</span><div><strong data-testid={`inquiry-name-${i.id}`}>{i.customer_name}</strong><p data-testid={`inquiry-property-${i.id}`}>{i.property_title}</p></div><time data-testid={`inquiry-date-${i.id}`}>{new Date(i.created_at).toLocaleDateString()}</time></div><p className="inquiry-message" data-testid={`inquiry-message-${i.id}`}>{i.message}</p><a className="text-link" href={`mailto:${i.customer_email}?subject=${encodeURIComponent('Re: '+i.property_title)}`} data-testid={`inquiry-reply-${i.id}`}>Reply by email<ArrowUpRight size={15}/></a></article>)}</div>:<Empty title="A quiet inbox, for now" text="Messages from interested customers will appear here."/>)}
  {tab==='payouts'&&<div className="payout-section"><div className="section-heading"><div><h2 data-testid="payouts-heading">Your earnings, clearly accounted for.</h2><p data-testid="payouts-description">Vacation and outing bookings include a 10% platform fee. Rental fee: {meta.rental_platform_fee*100}%. Transfers become available after check-out.</p></div></div><div className="payout-setup"><div><h3 data-testid="payout-account-title">Payout account</h3><p data-testid="payout-account-status">{data.payout_onboarding==='complete'?'Stripe account connected':'Connect and verify your Stripe account to receive transfers.'}</p>{!meta.stripe_configured&&<p className="notice" data-testid="payout-unavailable">Stripe setup is unavailable for the platform’s current country. No transfers can be made yet.</p>}</div><div className="payout-setup-actions"><label>Account country<select data-testid="payout-country" value={country} onChange={e=>setCountry(e.target.value)}><option value="KE">Kenya</option><option value="US">United States</option><option value="GB">United Kingdom</option><option value="CA">Canada</option><option value="AU">Australia</option><option value="AE">United Arab Emirates</option><option value="FR">France</option><option value="DE">Germany</option><option value="ZA">South Africa</option></select></label><Action variant="outline" data-testid="payout-onboarding" onClick={onboarding} busy={busy} disabled={!meta.stripe_configured}>Connect Stripe<ArrowUpRight size={15}/></Action></div></div><div className="payout-total" data-testid="transferred-total">Transferred to Stripe accounts: <strong>{money(data.transferred)}</strong><span>Not a confirmation of bank settlement.</span></div>{data.bookings.filter(b=>b.payment_status==='paid').length?<div className="payout-rows">{data.bookings.filter(b=>b.payment_status==='paid').map(b=><article className="payout-row" key={b.id}><strong data-testid={`payout-title-${b.id}`}>{b.property_title}</strong><span data-testid={`payout-gross-${b.id}`}>Booking {money(b.amount)}</span><span data-testid={`payout-fee-${b.id}`}>Platform fee {money(b.platform_fee)}</span><strong data-testid={`payout-net-${b.id}`}>You earn {money(b.host_payout)}</strong><span className="status-pill" data-testid={`payout-status-${b.id}`}>{b.payout_status}</span><Action variant="outline" data-testid={`payout-request-${b.id}`} busy={busy} disabled={!meta.stripe_configured||b.payout_status!=='pending'||b.check_out>new Date().toLocaleDateString('en-CA')} onClick={()=>payout(b.id)}>Request transfer</Action></article>)}</div>:<Empty title="Earnings start with your first booking" text="Confirmed payments and host transfers will be recorded here."/>}</div>}
  <Dialog open={!!deleting} onOpenChange={open=>!open&&setDeleting(null)}><DialogContent data-testid="delete-property-modal"><DialogTitle data-testid="delete-property-title">Delete this property?</DialogTitle><DialogDescription data-testid="delete-property-description">{deleting?.title} will no longer appear in the marketplace. Properties with upcoming bookings cannot be deleted.</DialogDescription><div className="dialog-actions"><Action variant="outline" onClick={()=>setDeleting(null)} data-testid="delete-property-cancel">Keep property</Action><Action className="danger-button" busy={busy} onClick={remove} data-testid="delete-property-confirm">Delete property</Action></div></DialogContent></Dialog>
  </main>;
}
export const BookingRows=({bookings})=>bookings.length?<div className="booking-rows">{bookings.map(b=><article className="booking-row" data-testid={`booking-row-${b.id}`} key={b.id}><div><Link to={`/properties/${b.property_id}`} data-testid={`booking-property-${b.id}`}>{b.property_title}<ArrowUpRight size={15}/></Link><p data-testid={`booking-customer-${b.id}`}>{b.customer_name} · {b.guests} guests</p></div><span data-testid={`booking-dates-${b.id}`}>{b.check_in} → {b.check_out}</span><strong data-testid={`booking-amount-${b.id}`}>{money(b.amount)}</strong><span className={`status-pill ${b.payment_status==='paid'?'positive':''}`} data-testid={`booking-status-${b.id}`}>{b.payment_status}</span></article>)}</div>:<Empty title="The next adventure is still ahead" text="Bookings will appear here after you start a reservation."/>;
export const MyBookings=()=>{const [data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{api.get('/bookings').then(r=>setData(r.data)).catch(e=>setError(errorText(e)));},[]);return <main className="container page"><div className="page-heading"><div><div className="eyebrow muted">MORE MEMORIES AHEAD</div><h1 data-testid="my-bookings-title">Your trips & bookings.</h1><p data-testid="my-bookings-description">Every confirmed stay, in one place.</p></div><Link className="action" to="/properties" data-testid="bookings-explore">Explore places<ArrowUpRight size={16}/></Link></div>{error?<ErrorState message={error}/>:data?<BookingRows bookings={data}/>:<Loading/>}</main>;};