import {useEffect,useState} from 'react';
import {useParams,useNavigate,useSearchParams,Link} from 'react-router-dom';
import {MapPin,BedDouble,Users,LandPlot,Check,ArrowUpRight,Send,Images} from 'lucide-react';
import {toast} from 'sonner';
import {api,errorText,imageUrl} from '../lib/api';
import {useApp} from '../context';
import {Back,Favorite,Loading,ErrorState,Action} from '../components/Common';
import {BookingPanel} from '../components/BookingPanel';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
export default function DetailsPage(){
  const {id}=useParams(),[params]=useSearchParams(),navigate=useNavigate(),{user}=useApp(),[p,setP]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[active,setActive]=useState(0),[gallery,setGallery]=useState(false),[contact,setContact]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[contactError,setContactError]=useState('');
  const preview=params.get('preview');
  useEffect(()=>{setP(null);setError('');setActive(0);api.get(preview?`/owner/properties/${id}`:`/properties/${id}`).then(r=>setP(r.data)).catch(e=>setError(errorText(e)));},[id,retry,preview]);
  if(error)return <main className="container page"><Back/><ErrorState message={error} retry={()=>setRetry(retry+1)}/></main>;
  if(!p)return <Loading/>;
  const openContact=()=>{if(!user){navigate('/signin',{state:{from:`/properties/${id}`}});return;}setContact(true);};
  const send=async e=>{e.preventDefault();setBusy(true);setContactError('');try{const r=await api.post(`/properties/${id}/inquiries`,{message});toast.success(r.data.message);setContact(false);setMessage('');}catch(e){setContactError(errorText(e));}finally{setBusy(false);}};
  return <main className="container page detail-page"><Back/><div className="detail-heading"><div><div className="detail-badges"><span className="badge gold" data-testid="detail-category">{p.category}</span>{p.is_sample&&<span className="badge" data-testid="detail-sample">Sample listing</span>}</div><h1 data-testid="detail-title">{p.title}</h1><p data-testid="detail-location"><MapPin size={16}/>{p.location}, {p.country}</p></div><Favorite property={p} prefix="detail"/></div><div className="property-gallery"><img src={imageUrl(p.images[active])} alt={`${p.title} — view ${active+1}`} data-testid="detail-main-image"/><button className="gallery-button" data-testid="show-all-photos" onClick={()=>setGallery(true)}><Images size={17}/>View {p.images.length} {p.images.length===1?'photo':'photos'}</button>{p.images.length>1&&<div className="gallery-thumbs">{p.images.map((im,i)=><button className={active===i?'active':''} key={i} data-testid={`gallery-thumbnail-${i}`} aria-label={`Show photo ${i+1}`} onClick={()=>setActive(i)}><img src={imageUrl(im)} alt={`Thumbnail ${i+1}`}/></button>)}</div>}</div><div className="detail-layout"><div className="detail-main"><div className="detail-summary" data-testid="detail-capacity">{p.category==='Land'?<span><LandPlot/>{p.size}</span>:<>{p.category!=='Outings'&&<span><BedDouble/>{p.bedrooms} bedrooms</span>}<span><Users/>{p.guests} guests</span></>}<span><MapPin/>{p.country}</span></div><section className="detail-section"><h2 data-testid="about-place-title">A place to make your own</h2><p className="property-description" data-testid="detail-description">{p.description}</p></section><section className="detail-section"><h2 data-testid="amenities-title">What this place offers</h2><div className="amenities">{p.amenities.length?p.amenities.map((a,i)=><span key={a} data-testid={`amenity-${i}`}><Check size={17}/>{a}</span>):<p data-testid="no-amenities">Contact the host for more details.</p>}</div></section><section className="host-profile detail-section"><span className="host-avatar">{p.host_name[0]}</span><div><h2 data-testid="detail-host">{p.category==='Land'?'Listed':'Hosted'} by {p.host_name}</h2><p data-testid="host-description">{p.is_sample?'Illustrative Global Estates collection':'Property owner on Global Estates'}</p></div>{user?.user_id===p.host_id&&<Link className="text-link" data-testid="detail-edit-property" to={`/list-property/${p.id}`}>Edit<ArrowUpRight size={16}/></Link>}</section></div><BookingPanel property={p} onContact={openContact}/></div>
  <Dialog open={gallery} onOpenChange={setGallery}><DialogContent className="gallery-modal" data-testid="gallery-modal"><DialogTitle data-testid="gallery-title">{p.title}</DialogTitle><DialogDescription data-testid="gallery-description">{p.is_sample?'Illustrative property photography.':'Property gallery'}</DialogDescription><div className="gallery-images">{p.images.map((im,i)=><img src={imageUrl(im)} key={i} alt={`${p.title} — photo ${i+1}`} data-testid={`gallery-full-image-${i}`}/>)}</div></DialogContent></Dialog>
  <Dialog open={contact} onOpenChange={setContact}><DialogContent data-testid="contact-modal"><DialogTitle data-testid="contact-title">Say hello to {p.host_name}</DialogTitle><DialogDescription data-testid="contact-description">Ask about {p.title}. Your name and email will be shared with the owner.</DialogDescription><form onSubmit={send}><label className="field">Your message<textarea data-testid="contact-message" value={message} onChange={e=>setMessage(e.target.value)} minLength={10} maxLength={3000} required rows={5} placeholder="Hi, I’d love to know more about your property…"/></label>{contactError&&<p className="form-error" data-testid="contact-error" role="alert">{contactError}</p>}<Action type="submit" busy={busy} className="full-width" data-testid="send-inquiry">Send inquiry<Send size={16}/></Action></form></DialogContent></Dialog>
  </main>;
}