import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight, ArrowUpRight, Globe2, Home as HomeIcon, Palmtree, Compass, LandPlot, Grid2X2, Check, MapPin} from 'lucide-react';
import {api, errorText, HERO} from '../lib/api';
import {useApp} from '../context';
import {SearchBar} from '../components/SearchBar';
import {PropertyCard, ErrorState, Empty} from '../components/Common';
const categories=[['All places',Grid2X2,''],['For rent',HomeIcon,'Rent'],['Vacation stays',Palmtree,'Vacation'],['Outings & experiences',Compass,'Outings'],['Land for sale',LandPlot,'Land']];
export default function HomePage(){
  const [category,setCategory]=useState(''), [country,setCountry]=useState(''), [properties,setProperties]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0); const {meta}=useApp();
  useEffect(()=>{let active=true; setLoading(true); setError(''); api.get('/properties',{params:{category,country,limit:4,sort:'newest'}}).then(r=>{if(active)setProperties(r.data.properties);}).catch(e=>{if(active)setError(errorText(e));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[category,country,retry]);
  const allLink='/properties?'+new URLSearchParams({...category&&{category},...country&&{country}}).toString();
  return <>
    <section className="hero" style={{backgroundImage:`url(${HERO})`}} data-testid="home-hero"><div className="hero-shade"/><div className="container hero-inner"><div className="hero-content"><div className="eyebrow" data-testid="hero-eyebrow"><span/> EXTRAORDINARY PLACES. ENDLESS POSSIBILITIES.</div><h1 data-testid="hero-title">Find Your Place<br/>in the <em>World.</em></h1><p data-testid="hero-description">Discover homes, vacation stays, unique outings and<br className="desktop-only"/> land opportunities around the world.</p></div><div className="hero-location" data-testid="hero-image-caption"><MapPin size={15}/><span>A little closer to paradise</span></div><SearchBar/></div></section>
    <div className="discovery-strip"><div className="container discovery-inner"><div className="category-tabs" role="tablist" aria-label="Explore categories">{categories.map(([name,Icon,value])=><button role="tab" aria-selected={category===value} className={category===value?'selected':''} key={name} data-testid={`home-category-${value||'all'}`} onClick={()=>setCategory(value)}><Icon size={20} strokeWidth={1.5}/>{name}</button>)}</div><label className="country-select"><Globe2 size={17}/><select aria-label="Filter by country" data-testid="home-country" value={country} onChange={e=>setCountry(e.target.value)}><option value="">All countries</option>{meta.countries.map(c=><option key={c}>{c}</option>)}</select></label></div></div>
    <section className="container section featured-section"><div className="section-heading"><div><div className="eyebrow muted" data-testid="featured-eyebrow">DISCOVER SOMETHING SPECIAL</div><h2 data-testid="featured-title">Places worth finding<span className="accent-dot">.</span></h2><p data-testid="featured-description">A new address. A change of scenery. Your next chapter starts here.</p></div><Link className="text-link" to={allLink} data-testid="home-view-all">View all properties<ArrowRight size={17}/></Link></div>{loading?<div className="property-grid" data-testid="property-skeletons">{[1,2,3,4].map(i=><div className="card-skeleton" key={i}/>)}</div>:error?<ErrorState message={error} retry={()=>setRetry(retry+1)}/>:properties.length?<div className="property-grid">{properties.map(p=><PropertyCard key={p.id} property={p}/>)}</div>:<Empty/>}<p className="sample-note" data-testid="sample-listings-notice">Sample listings are illustrative and cannot be booked. Real owner listings appear here as they’re added.</p></section>
    <section className="destination-section"><div className="container section"><div className="section-heading"><div><div className="eyebrow muted" data-testid="destinations-eyebrow">NEAR OR FAR. MAKE IT YOURS.</div><h2 data-testid="destinations-title">Where will you go next?</h2></div><Link className="text-link" to="/properties?category=Vacation" data-testid="explore-stays">Explore stays<ArrowRight size={17}/></Link></div><div className="destination-grid">{[['Kenya','Wild beauty. Warm welcomes.','photo-1535940360221-641a69c43bac'],['Indonesia','A slower kind of paradise.','photo-1596178067639-5c6e68aea6dc'],['France','A place to fall in love with.','photo-1738168279272-c08d6dd22002']].map(([name,description,img])=><Link to={`/properties?country=${name}`} key={name} className="destination" data-testid={`destination-${name.toLowerCase()}`}><img src={`https://images.unsplash.com/${img}?auto=format&fit=crop&w=900&q=80`} alt={`${name} collection — illustrative photograph`} loading="lazy"/><div><span>{description}</span><h3>{name}</h3></div><span className="destination-arrow"><ArrowUpRight size={23}/></span></Link>)}</div></div></section>
    <section className="container host-section"><div className="host-symbol"><HomeIcon size={44} strokeWidth={1}/><span>✦</span></div><div className="host-copy"><div className="eyebrow muted" data-testid="host-eyebrow">YOUR PROPERTY. A WORLD OF OPPORTUNITY.</div><h2 data-testid="host-cta-title">Great places deserve to be discovered.</h2><p data-testid="host-cta-description">Open your doors to a global audience. Start with a free listing.</p><div className="host-perks" data-testid="host-benefits"><span><Check size={14}/>Free to get started</span><span><Check size={14}/>You’re in control</span></div></div><Link className="action host-button" to="/list-property" data-testid="home-become-host">List your property<ArrowUpRight size={17}/></Link></section>
  </>;
}