import {useEffect,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {Upload,Plus,X,ArrowRight,Check,ImagePlus} from 'lucide-react';
import {toast} from 'sonner';
import {useApp} from '../context';
import {api,errorText,imageUrl} from '../lib/api';
import {Action,Field,Back,Loading,ErrorState} from '../components/Common';
const amenityOptions=['Wi-Fi','Kitchen','Free parking','Swimming pool','Air conditioning','Outdoor space','Beach access','Scenic views','Pet friendly','Security','Water supply','Electricity'];
const initial={title:'',category:'Rent',location:'',country:'Kenya',description:'',price:'',bedrooms:1,guests:2,amenities:[],images:[],contact_email:'',size:'',status:'active'};
export default function ListingForm(){
  const {id}=useParams(),{user,meta}=useApp(),navigate=useNavigate(),[form,setForm]=useState({...initial,contact_email:user.email}),[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[loading,setLoading]=useState(!!id),[error,setError]=useState(''),[loadError,setLoadError]=useState('');
  useEffect(()=>{if(id)api.get(`/owner/properties/${id}`).then(r=>{const next={};Object.keys(initial).forEach(k=>next[k]=r.data[k]??initial[k]);setForm(next);}).catch(e=>setLoadError(errorText(e))).finally(()=>setLoading(false));},[id]);
  const change=(k,v)=>setForm(f=>({...f,[k]:v}));
  const addUrl=()=>{if(!/^https:\/\/[^\s]+$/.test(url)){toast.error('Enter a valid HTTPS image URL.');return;}if(form.images.length>=12){toast.error('Add up to 12 images.');return;}change('images',[...form.images,url]);setUrl('');};
  const upload=async e=>{const files=Array.from(e.target.files||[]);if(files.length+form.images.length>12){toast.error('Add up to 12 images.');return;}setUploading(true);try{const images=[];for(const file of files){const data=new FormData();data.append('file',file);images.push((await api.post('/upload',data,{timeout:120000})).data.url);}setForm(f=>({...f,images:[...f.images,...images]}));toast.success('Photos uploaded');}catch(e){toast.error(errorText(e));}finally{setUploading(false);e.target.value='';}};
  const submit=async e=>{e.preventDefault();if(!form.images.length){setError('Please add at least one property image.');return;}setBusy(true);setError('');try{const body={...form,price:Number(form.price),bedrooms:form.category==='Land'||form.category==='Outings'?0:Number(form.bedrooms),guests:Number(form.guests)};const r=await api[id?'put':'post'](id?`/properties/${id}`:'/properties',body);toast.success('Property saved successfully.');navigate(r.data.status==='active'?`/properties/${r.data.id}`:'/dashboard');}catch(e){setError(errorText(e));}finally{setBusy(false);}};
  if(loading)return <Loading/>;if(loadError)return <ErrorState message={loadError}/>;
  return <main className="container page listing-page"><Back to="/dashboard" label="Back to dashboard"/><div className="page-heading"><div><div className="eyebrow muted" data-testid="listing-eyebrow">OPEN YOUR DOORS TO THE WORLD</div><h1 data-testid="listing-heading">{id?'Make it your own.':'Every place has a story.'}</h1><p data-testid="listing-description">{id?'Keep your property details fresh and welcoming.':'Tell yours. Create your free property listing.'}</p></div><span className="badge gold" data-testid="listing-plan">Free listing · KSh 0</span></div><form onSubmit={submit} className="listing-form"><section><div className="form-section-title"><span>01</span><div><h2 data-testid="listing-basics-title">The essentials</h2><p>A great first impression starts here.</p></div></div><Field label="Property title" id="listing-title" required minLength={5} maxLength={120} placeholder="e.g. A peaceful garden villa in Diani" value={form.title} onChange={e=>change('title',e.target.value)}/><div className="form-grid"><Field label="Category" id="listing-category"><select id="listing-category" data-testid="listing-category" value={form.category} onChange={e=>change('category',e.target.value)}>{['Rent','Vacation','Outings','Land'].map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Country" id="listing-country"><select id="listing-country" data-testid="listing-country" value={form.country} onChange={e=>change('country',e.target.value)} required>{meta.countries.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="City / location" id="listing-location" required minLength={2} maxLength={120} placeholder="e.g. Diani Beach" value={form.location} onChange={e=>change('location',e.target.value)}/><Field label={`Price in KSh ${form.category==='Rent'?'per month':form.category==='Vacation'?'per night':form.category==='Outings'?'per person / day':'(total)'}`} id="listing-price" type="number" min="1" max="100000000000" step="0.01" required placeholder="0.00" value={form.price} onChange={e=>change('price',e.target.value)}/>{form.category==='Land'?<Field label="Land size" id="listing-size" placeholder="e.g. 0.5 acres" required maxLength={80} value={form.size} onChange={e=>change('size',e.target.value)}/>:<>{form.category!=='Outings'&&<Field label="Bedrooms" id="listing-bedrooms" type="number" min="0" max="100" required value={form.bedrooms} onChange={e=>change('bedrooms',e.target.value)}/>}<Field label="Maximum guests" id="listing-guests" type="number" min="1" max="500" required value={form.guests} onChange={e=>change('guests',e.target.value)}/></>}</div><Field label="Description" id="listing-description"><textarea id="listing-description" data-testid="listing-description-input" required minLength={30} maxLength={8000} rows={5} placeholder="What makes your place special? Share the space, surroundings, and little details guests will love." value={form.description} onChange={e=>change('description',e.target.value)}/></Field></section>
  <section><div className="form-section-title"><span>02</span><div><h2 data-testid="listing-amenities-title">The little extras</h2><p>What can guests look forward to?</p></div></div><div className="amenity-choices">{amenityOptions.map((a,i)=><label key={a} className={form.amenities.includes(a)?'checked':''}><input type="checkbox" data-testid={`listing-amenity-${i}`} checked={form.amenities.includes(a)} onChange={()=>change('amenities',form.amenities.includes(a)?form.amenities.filter(v=>v!==a):[...form.amenities,a])}/><span>{a}</span>{form.amenities.includes(a)&&<Check size={14}/>}</label>)}</div></section>
  <section><div className="form-section-title"><span>03</span><div><h2 data-testid="listing-photos-title">Let your place shine</h2><p>JPEG, PNG, or WebP · Up to 12 photos · 10 MB each</p></div></div><label className={`upload-area ${uploading?'uploading':''}`}><input data-testid="listing-image-upload" type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={uploading} onChange={upload}/><ImagePlus size={28}/><strong>{uploading?'Uploading your photos…':'Choose property photos'}</strong><span>Your first photo will be the cover image.</span></label><div className="image-url-row"><input aria-label="HTTPS image URL" data-testid="listing-image-url" type="url" placeholder="Or paste an HTTPS image URL" value={url} onChange={e=>setUrl(e.target.value)}/><Action type="button" variant="outline" data-testid="listing-add-image-url" onClick={addUrl}><Plus size={16}/>Add</Action></div><div className="listing-image-previews">{form.images.map((im,i)=><div key={`${im}-${i}`}><img src={imageUrl(im)} alt={`Property photo ${i+1}`}/><button type="button" data-testid={`remove-listing-image-${i}`} aria-label={`Remove photo ${i+1}`} onClick={()=>change('images',form.images.filter((_,n)=>n!==i))}><X size={15}/></button>{i===0&&<span>Cover</span>}</div>)}</div></section>
  <section><div className="form-section-title"><span>04</span><div><h2 data-testid="listing-contact-title">Make the connection</h2><p>Your contact email is private. Inquiries arrive in your dashboard.</p></div></div><div className="form-grid"><Field label="Contact email" id="listing-contact" type="email" required value={form.contact_email} onChange={e=>change('contact_email',e.target.value)}/>{id&&<Field label="Listing status" id="listing-status"><select data-testid="listing-status" id="listing-status" value={form.status} onChange={e=>change('status',e.target.value)}><option value="active">Active — visible to everyone</option><option value="paused">Paused — hidden from discovery</option></select></Field>}</div></section>{error&&<p data-testid="listing-error" role="alert" className="form-error">{error}</p>}<div className="form-submit-row"><span data-testid="listing-free-note">No listing fee. Your place, your possibilities.</span><Action data-testid="listing-submit" busy={busy} disabled={uploading} type="submit">{id?'Save changes':'List my property'}<ArrowRight size={18}/></Action></div></form></main>;
}