import {useEffect,useState} from 'react';
import {Link,useSearchParams,useNavigate} from 'react-router-dom';
import {Check,ArrowRight,ShieldCheck,CheckCircle2,Clock3,XCircle} from 'lucide-react';
import {toast} from 'sonner';
import {useApp} from '../context';
import {api,errorText,money} from '../lib/api';
import {Action,Back,Loading} from '../components/Common';
export function PlansPage(){
  const [params]=useSearchParams(),property_id=params.get('property'),{meta}=useApp(),navigate=useNavigate(),[busy,setBusy]=useState('');
  const choose=async plan=>{if(plan==='Free'){navigate(property_id?'/dashboard':'/list-property');return;}setBusy(plan);try{const r=await api.post('/checkout',{property_id,plan});window.location.assign(r.data.checkout_url);}catch(e){toast.error(errorText(e));setBusy('');}};
  return <main className="container page plans-page"><Back to="/dashboard" label="Back to dashboard"/><div className="page-heading"><div><div className="eyebrow muted" data-testid="plans-eyebrow">MAKE ROOM FOR MORE POSSIBILITIES</div><h1 data-testid="plans-title">A little more visibility.</h1><p data-testid="plans-description">Choose the right home for your property listing. One-time pricing per property.</p></div></div>{!meta.stripe_configured&&<div className="notice plans-notice" data-testid="plans-payment-notice">Paid promotions are unavailable while Stripe account setup is blocked. Free listings remain fully available. No payment or paid placement is being simulated.</div>}<div className="plans-grid">{[['Free',0,['Property listing','Property photo gallery','Owner dashboard','Customer inquiries']],['Featured',500,['Everything in Free','Featured property badge','Higher recommended placement']],['Premium',2000,['Everything in Featured','Premium property badge','Top recommended placement']]].map(([name,price,benefits])=><article className={`plan ${name==='Premium'?'premium':''}`} key={name}><span className="plan-icon">{name==='Free'?<ShieldCheck size={25}/>:name==='Featured'?'✦':'✧'}</span><h2 data-testid={`plan-name-${name}`}>{name}</h2><div className="plan-price" data-testid={`plan-price-${name}`}>{money(price)}<span>one-time</span></div><ul>{benefits.map((b,i)=><li key={b} data-testid={`plan-${name}-benefit-${i}`}><Check size={16}/>{b}</li>)}</ul><Action variant={name==='Premium'?'default':'outline'} className="full-width" busy={busy===name} disabled={name!=='Free'&&(!meta.stripe_configured||!property_id)} data-testid={`choose-plan-${name}`} onClick={()=>choose(name)}>{name==='Free'?'Continue with Free':`Choose ${name}`}<ArrowRight size={16}/></Action></article>)}</div></main>;
}
export function PaymentPage({cancelled=false}){
  const [params]=useSearchParams(),[status,setStatus]=useState('pending'),[error,setError]=useState(''),[retry,setRetry]=useState(0),{user}=useApp();
  const session=params.get('session_id'),transaction=params.get('transaction_id');
  useEffect(()=>{let active=true,timer;setError('');if(cancelled){setStatus('cancelled');if(transaction&&user)api.post(`/checkout/cancel/${transaction}`).catch(e=>{if(active)setError(errorText(e));});return()=>{active=false;};}if(!session){setError('No payment session was provided.');return;}let count=0;const poll=async()=>{try{const r=await api.get('/checkout/status',{params:{session_id:session}});if(!active)return;setStatus(r.data.payment_status);if(r.data.payment_status==='pending'&&count++<10)timer=setTimeout(poll,2000);}catch(e){if(active)setError(errorText(e));}};poll();return()=>{active=false;clearTimeout(timer);};},[cancelled,session,transaction,user,retry]);
  const paid=status==='paid';
  return <main className="container page payment-page"><div className={`payment-symbol ${paid?'success':''}`}>{paid?<CheckCircle2 size={48}/>:cancelled?<XCircle size={48}/>:<Clock3 size={48}/>}</div><h1 data-testid="payment-title">{paid?'You’re all set.':cancelled?'Checkout cancelled.':'Checking your payment.'}</h1><p data-testid="payment-message">{paid?'Your payment has been confirmed by Stripe and your booking or listing upgrade has been recorded.':cancelled?'Checkout was not completed. Check your bookings for the latest payment status.':'Your booking or upgrade is not confirmed until Stripe verifies payment.'}</p>{error&&<p className="form-error" data-testid="payment-error" role="alert">{error}</p>}<div className="payment-actions">{!paid&&!cancelled&&<Action onClick={()=>setRetry(retry+1)} data-testid="payment-recheck">Check again</Action>}<Link to="/bookings" className="action" data-testid="payment-view-bookings">My bookings<ArrowRight size={16}/></Link><Link to="/dashboard" className="text-link" data-testid="payment-dashboard">Owner dashboard<ArrowRight size={15}/></Link></div></main>;
}