import {useEffect, useState} from 'react';
import {useSearchParams, Link} from 'react-router-dom';
import {SlidersHorizontal, X, ArrowLeft, ArrowRight, Heart} from 'lucide-react';
import {api, errorText} from '../lib/api';
import {useApp} from '../context';
import {SearchBar} from '../components/SearchBar';
import {PropertyCard, ErrorState, Empty, Action, Loading} from '../components/Common';
export default function PropertiesPage({saved=false}){
  const [params,setParams]=useSearchParams(),{meta,favorites}=useApp(),[data,setData]=useState({properties:[],total:0,pages:0}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filtersOpen,setFiltersOpen]=useState(()=>window.matchMedia('(min-width:761px)').matches),[retry,setRetry]=useState(0); const query=params.toString();
  const update=(key,value)=>{const next=new URLSearchParams(params); value?next.set(key,value):next.delete(key); if(key!=='page')next.delete('page'); setParams(next);};
  useEffect(()=>{if(saved){setLoading(false);return;}let active=true;setLoading(true);setError('');api.get('/properties?'+query).then(r=>{if(active)setData(r.data);}).catch(e=>{if(active)setError(errorText(e));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[query,saved,retry]);
  const props=saved?favorites:data.properties, category=params.get('category');
  return <main className="container page properties-page"><div className="page-heading"><div><div className="eyebrow muted" data-testid="browse-eyebrow">{saved?'KEEP THE POSSIBILITIES CLOSE':'YOUR NEXT CHAPTER STARTS HERE'}</div><h1 data-testid="browse-title">{saved?'Your saved places':category?{Rent:'Find a place to call home',Vacation:'A stay less ordinary',Outings:'Go beyond the everyday',Land:'Room for your next big idea'}[category]||'Explore properties':'A world of possibilities'}</h1><p data-testid="browse-description">{saved?'The places you love, all in one place.':'Discover the right place, wherever life takes you.'}</p></div>{saved&&<Heart size={35} strokeWidth={1}/>}</div>
  {!saved&&<><SearchBar key={`${params.get('location')}-${category}`} initialLocation={params.get('location')||''} initialCategory={category||''} compact/><div className="browse-toolbar"><button className="filter-toggle" data-testid="filters-toggle" onClick={()=>setFiltersOpen(!filtersOpen)} aria-expanded={filtersOpen}><SlidersHorizontal size={16}/>Filters</button><span data-testid="result-count">{loading?'Searching…':`${data.total} ${data.total===1?'place':'places'} to discover`}</span><label className="sort-label">Sort by<select aria-label="Sort properties" data-testid="sort-select" value={params.get('sort')||'newest'} onChange={e=>update('sort',e.target.value)}><option value="newest">Newest first</option><option value="recommended">Recommended</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option></select></label></div><div className={`filter-bar ${filtersOpen?'filters-open':''}`}><label>Country<select data-testid="filter-country" value={params.get('country')||''} onChange={e=>update('country',e.target.value)}><option value="">All countries</option>{meta.countries.map(c=><option key={c}>{c}</option>)}</select></label><label>Category<select data-testid="filter-category" value={category||''} onChange={e=>update('category',e.target.value)}><option value="">All types</option>{['Rent','Vacation','Outings','Land'].map(c=><option key={c}>{c}</option>)}</select></label><label>Min price (KSh)<input type="number" min="0" placeholder="No minimum" data-testid="filter-min-price" value={params.get('minPrice')||''} onChange={e=>update('minPrice',e.target.value)}/></label><label>Max price (KSh)<input type="number" min="0" placeholder="No maximum" data-testid="filter-max-price" value={params.get('maxPrice')||''} onChange={e=>update('maxPrice',e.target.value)}/></label><label>Bedrooms<select data-testid="filter-bedrooms" value={params.get('bedrooms')||''} onChange={e=>update('bedrooms',e.target.value)}><option value="">Any</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}+</option>)}</select></label><label>Guests<select data-testid="filter-guests" value={params.get('guests')||''} onChange={e=>update('guests',e.target.value)}><option value="">Any</option>{[1,2,4,6,8,10].map(n=><option key={n} value={n}>{n}+</option>)}</select></label><button className="clear-filters" title="Clear filters" aria-label="Clear filters" data-testid="clear-filters" onClick={()=>setParams({})}><X size={17}/></button></div></>}
  {loading?<Loading/>:error?<ErrorState message={error} retry={()=>setRetry(retry+1)}/>:props.length?<div className="property-grid browse-grid">{props.map(p=><PropertyCard key={p.id} property={p}/>)}</div>:<Empty title={saved?'Your next favorite is out there':'No places found'} text={saved?'Save a place that catches your eye and find it here.':'Try a different location, country, or price range.'}>{saved?<Link className="action" to="/properties" data-testid="saved-explore">Explore properties<ArrowRight size={16}/></Link>:<Action data-testid="empty-clear-filters" onClick={()=>setParams({})}>Clear filters</Action>}</Empty>}
  {!saved&&data.pages>1&&<div className="pagination"><Action variant="outline" data-testid="previous-page" disabled={Number(params.get('page')||1)<=1} onClick={()=>update('page',String(Number(params.get('page')||1)-1))}><ArrowLeft size={16}/>Previous</Action><span data-testid="page-number">Page {params.get('page')||1} of {data.pages}</span><Action variant="outline" data-testid="next-page" disabled={Number(params.get('page')||1)>=data.pages} onClick={()=>update('page',String(Number(params.get('page')||1)+1))}>Next<ArrowRight size={16}/></Action></div>}
  </main>;
}